### ISSUE TITLE
Steemit Wallet makefile problems

### ISSUE THREAD

**Issue by faddat** [steemit/steem#570]
/root/steem/libraries/wallet/wallet.cpp:50:37: fatal error: steemit/wallet/wallet.hpp: No such file or directory
compilation terminated.
libraries/wallet/CMakeFiles/steemit_wallet.dir/build.make:74: recipe for target 'libraries/wallet/CMakeFiles/steemit_wallet.dir/wallet.cpp.o' failed
make[2]: *** [libraries/wallet/CMakeFiles/steemit_wallet.dir/wallet.cpp.o] Error 1
CMakeFiles/Makefile2:2466: recipe for target 'libraries/wallet/CMakeFiles/steemit_wallet.dir/all' failed
make[1]: *** [libraries/wallet/CMakeFiles/steemit_wallet.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mvandeberg** [comment]
Can you please expand on what build options you are using? In source or out of source build? cmake version?

**Comment by faddat** [comment]
Happy to!

cmake @ 3.6.3

Don't know what an in or out of source build is, unfortunately.  If you mean did I make a folder called build and then do something like cmake .., answer is yes.  

For my build, I made a script from the following, taken directly from the building.md page:

```bash
# Required packages
sudo apt-get install -y \
    autoconf \
    automake \
    cmake \
    g++ \
    git \
    libssl-dev \
    libtool \
    make

# Boost packages (also required)
sudo apt-get install -y \
    libboost-chrono-dev \
    libboost-context-dev \
    libboost-coroutine-dev \
    libboost-date-time-dev \
    libboost-filesystem-dev \
    libboost-iostreams-dev \
    libboost-locale-dev \
    libboost-program-options-dev \
    libboost-serialization-dev \
    libboost-signals-dev \
    libboost-system-dev \
    libboost-test-dev \
    libboost-thread-dev

# Optional packages (not required, but will make a nicer experience)
sudo apt-get install -y \
    doxygen \
    libncurses5-dev \
    libreadline-dev \
    perl

git clone https://github.com/steemit/steem
cd steem
git submodule update --init --recursive
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j$(nproc) steemd
make -j$(nproc) cli_wallet
# optional
make install  # defaults to /usr/local
```

**Comment by mapalanet** [comment]
same problem
`/steem/libraries/wallet/wallet.cpp:50:37: fatal error: steemit/wallet/wallet.hpp: No such file or directory
compilation terminated.
`

**Comment by theoreticalbts** [comment]
What version are you trying to build?  Please paste the output of `git log -1`

**Comment by theoreticalbts** [comment]
I was able to reproduce this on develop -- 2fdf7c5a23c90ad7d10f7447fc36cd2fc5624e3c -- I'm going to use `git bisect` to figure out exactly when it stopped building and proceed from there.

**Comment by theoreticalbts** [comment]
Bisect returned a huge list of potential culprit commits:

```
# possible first bad commit: [72eb10141ed0c25223dba91b964cb0a7aabcb648] Compilation and unit test progress
# possible first bad commit: [5aa242427f68f008d4fb51913f07a8a87401cdc9] Various minor compilation fixes
# possible first bad commit: [67ac4cd2f3c68027b0681d8792358beca5d4fa64] Comment out binary methods until more fc::raw::pack() implementations are provided
# possible first bad commit: [9a91e6ed3d8d8248c5d5d15e97d7afd208feb42f] Add generic object manipulation methods to database
# possible first bad commit: [be40df21b7eddc6a17f56ac9978eb4fea6c4824c] Add generic object manipulation methods to indexes
# possible first bad commit: [bf20d7ec0c799b675d2a6205d3fdf15396b6f76e] Add get_schema() to indexes
# possible first bad commit: [e13e94fd2b6801eae7f6fee706d1482c9cab21fe] Copy schema to separate library
# possible first bad commit: [d3896bf19a78b2fb84815619d2d9e227172c68df] Fix a few more refactor bugs
# possible first bad commit: [a97d9a15fe46f5081a7eb22ec4e373d239133cba] Remove db directory
# possible first bad commit: [39cf5f7329a44af34622084bec985e8eecd2509d] Building up to unit tests
# possible first bad commit: [52ba8571738044e0547a2ee9ad8a4b2e2bd96a29] generic_id specification
# possible first bad commit: [23ccd52a5da0d805d594dabc07dd58137ebb1f10] Clean up startup and shutdown logic
# possible first bad commit: [0a81167546460d904568c2443adedc253722e484] Refactor account auth into its own object
# possible first bad commit: [1445027dc6a91270b838232005b912c7f11cac80] Merge commit '313ac8d566af0ea33a574269fc0c5c292d253f5f' into 20160928-chain-refactor
# possible first bad commit: [896e68fceb2b4b15904439ee3f17f6271ad6b81b] Fixed a bug in the undo state. steamd appears to be working on the live network.
# possible first bad commit: [313ac8d566af0ea33a574269fc0c5c292d253f5f] Fix next_id undo bug #504
# possible first bad commit: [1bb269011a2158e107251c2cd150fbca4184da28] Implement unit test for next_id undo bug #504
# possible first bad commit: [78543aed802143b45ecd1ae35bf704a8ea695ee7] Add database_tests target and make it compile
# possible first bad commit: [ea1487879ad15991b54094ac30efafe72af54e37] Add missing comments in generic_index::squash()
# possible first bad commit: [d2fb34540ccba73ee4ab195777c3f961cf730a48] Add doc comment to generic_index::emplace()
# possible first bad commit: [e5e5d60fd2ca070d8d9103730ce37f27cc863ddf] Fix gcc compile error
# possible first bad commit: [e76207ae92da7c8878db237381aeed6125954a0b] Reindexes properly
# possible first bad commit: [f2f87ac17963f4f607bf6f25c0461d8abe0f7ba2] Steamed syncs. Segfailt when live
# possible first bad commit: [56f6a726ebff3b7505f23a3a36d65ce1f5cd5931] Merge branch '463-shared-db-sync' into 20160928-chain-refactor
# possible first bad commit: [184c75c6c8e41351b735ae4f306f0aa44dbb75e3] Merge branch '465-auth-validate' into 20160928-chain-refactor
# possible first bad commit: [4bb8af74accce225a4694ccce3e5b0117c2dcf67] Progress on syncing
# possible first bad commit: [ee40b9856906abcf50449828a6cd56292bbc1385] reindexes but does not sync
# possible first bad commit: [11d9b6f7b05803108671ed363a215ae4e7c68c64] Merge commit '0e3d379033a2c57e72bff4dbad97f5ceaa442386' into 20160928-chain-refactor Progress reindexing...
# possible first bad commit: [38da5951a872df65238d0e8f0df3deaabf158b58] progress...
# possible first bad commit: [6b05b5b2ad14f746c98d2221280472801cd5c9d4] steamd builds
# possible first bad commit: [19878899d8751b4a206d1fa18f088a0ffbb52f7f] Need to fix linking
# possible first bad commit: [3d07a8c61b92b1ad9c32349ec11608b1417f607c] database api and more plugins compile
# possible first bad commit: [0aa9312d7554868961e7840f129eb0c0a78b3464] follow plugin and shared authority
# possible first bad commit: [f465e3991d38b221ebca06a4f7ab0611ed4deb3e] tags plugin compiles
# possible first bad commit: [b53049c0999b75fa8441cdf9ed9d28e6d212004f] Compilation now requires plugins
# possible first bad commit: [f1fb3d76cbe63eda88978bffbe39b2ce67067ec0] More progress...
# possible first bad commit: [984be2dc289a910822a8ab2ed473b1d1fc4e4eb1] progress...
```

**Comment by theoreticalbts** [comment]
According to [this diff](https://github.com/steemit/steem/compare/3d28d5a95821434a4ba6c63c472b2563e714d29d...72eb10141ed0c25223dba91b964cb0a7aabcb648#diff-d04d49da80dadea92f40db0e7557f3e9) we see that `libraries/wallet/CMakeLists.txt` was changed.  There are no files in the binary directory so let's change that to `CMAKE_CURRENT_SOURCE_DIR`, that seems to fix this problem.

**Comment by sneak** [comment]
Thanks for tracking this down, @theoreticalbts. Glad to see this fixed.

**Comment by mvandeberg** [comment]
Merged
