### ISSUE TITLE
make not working with boost 1.68

### ISSUE THREAD

**Issue by marekwyszynski** [steemit/steem#3253]
Environment: Ubuntu 16.04
When I'm running `make`, I get the following output:
 [19%] Building CXX object libraries/fc/tests/CMakeFiles/all_tests.dir/all_tests.cpp.o
In file included from /root/opt/boost_1_67_0/include/boost/test/unit_test_log.hpp:25:0,
                 from /root/opt/boost_1_67_0/include/boost/test/tools/old/impl.hpp:19,
                 from /root/opt/boost_1_67_0/include/boost/test/test_tools.hpp:46,
                 from /root/opt/boost_1_67_0/include/boost/test/unit_test.hpp:18,
                 from /root/steem/steem/libraries/fc/tests/all_tests.cpp:2:
/root/opt/boost_1_67_0/include/boost/test/unit_test_log.hpp:227:28: error: ‘boost::unit_test::{anonymous}::unit_test_log’ defined but not used [-Werror=unused-variable]
 BOOST_TEST_SINGLETON_INST( unit_test_log )
                            ^
/root/opt/boost_1_67_0/include/boost/test/utils/trivial_singleton.hpp:67:36: note: in definition of macro ‘BOOST_TEST_SINGLETON_INST’
 namespace { BOOST_JOIN( inst, _t)& inst = BOOST_JOIN( inst, _t)::instance(); }
                                    ^
cc1plus: all warnings being treated as errors
libraries/fc/tests/CMakeFiles/all_tests.dir/build.make:62: recipe for target 'libraries/fc/tests/CMakeFiles/all_tests.dir/all_tests.cpp.o' failed
make[2]: *** [libraries/fc/tests/CMakeFiles/all_tests.dir/all_tests.cpp.o] Error 1
CMakeFiles/Makefile2:420: recipe for target 'libraries/fc/tests/CMakeFiles/all_tests.dir/all' failed
make[1]: *** [libraries/fc/tests/CMakeFiles/all_tests.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Gandalf-the-Grey** [comment]
Please consider using boost version that is included with your distribution, unless you know what you are doing. Stable branch works perfectly fine with `Ubuntu 16.04 LTS`, for mira versions, there's upcoming upgrade to `Ubuntu 18.04 LTS` (with `boost` version `1.65.1`)
There's no point (and waste of time/resources) in providing compatibility for full matrix of component versions.
