### ISSUE TITLE
Building on Ubuntu 17.04 broken

### ISSUE THREAD

**Issue by reppolice** [steemit/steem#1090]
The building.md instructions presumably are missing a "cd .." just before the make commands. Neither of the build targets succeeds, with errors like this:

steem/libraries/fc/src/thread/context.hpp:103:25: error: ‘fcontext_t’ in namespace ‘bc’ does not name a type
      my_context(new bc::fcontext_t),

Any ideas what this is? Boost too new?

**Comment by Gandalf-the-Grey** [comment]
`cd ..` is not needed there
you go to `build` directory and use cmake on `..`
then `make` in current:
```
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j$(nproc) steemd
```

As per [building doc](https://github.com/steemit/steem/blob/master/doc/building.md), 
> Steem requires Boost 1.58 (as in Ubuntu 16.04) and works with versions up to 1.60 (including). 

So if you are using packages provided by Ubuntu 17.04 (AFAIR 1.62) it won't work.

**Comment by mvandeberg** [comment]
From what I can tell Ubuntu 17.04 has boost 1.62 by default, which is currently not supported. You will need to build boost 1.60 from source.

**Comment by mvandeberg** [comment]
Alternatively, we provide pre-built docker images. Feel free to use those instead of compiling from source.

**Comment by mvandeberg** [comment]
Because Ubuntu 17.04 does not prevent compiling required packages and because it supports our Docker images without problem, I am closing this issue.

**Comment by cosmicboy123** [comment]
Sorry to bother you but i want to know the status about this issue i got the same error mentioned by reppolice in May, I need a work around on this because am trying to compile steemd on FreeBSD 11.0 amd64, right know am stuck with this error, any comments? forget docker, in this case is not an option.

**Comment by mvandeberg** [comment]
All of the versions of dependencies can be build on those systems, but may not come with the default package manager. You will need to build whichever dependency is failing from source. My guess is you are using a newer version of boost. Build 1.60 from source.

**Comment by cosmicboy123** [comment]
You are right FreeBSD 11.0 come with boost 1.63  y the last freebsd ports update its 1.64 :( i  will try with 1.60 from source i will let you know the result. 
By the way in the future the steem code will support boost 1.63 or 1.64? there are plans for that?

**Comment by mvandeberg** [comment]
We have some code that was broken by Boost 1.61 and are working on replacing it, but have no estimate on when that will be.

**Comment by cosmicboy123** [comment]
Thanks for your feed back I will try with the 1.60 version thanks again!
I will be looking to it.

greetings from Mérida, Yucatán, México.
cosmicboy123.



On Tuesday, August 1, 2017, 9:51:05 AM CDT, Michael Vandeberg <notifications@github.com> wrote:


We have some code that was broken by Boost 1.61 and are working on replacing it, but have no estimate on when that will be.

**Comment by RDTHAKOR** [comment]
steem/libraries/fc/src/thread/context.hpp:103:25: error: ‘fcontext_t’ in namespace ‘bc’ does not name a type
my_context(new bc::fcontext_t),

Any ideas what this is? Boost too new?

**Comment by mvandeberg** [comment]
As mentioned earlier, that is caused by a boost version >1.60

In a later version of steem will will fix this compatibility problem.
