### ISSUE TITLE
[shared-db] Fails to build on Ubuntu 16.04.1 LTS + (boost 1.60) - atomic needs to be explicitly included

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#548]
```
In file included from /home/steem/src/steem/libraries/db2/include/graphene/db2/database.hpp:24:0,
                 from /home/steem/src/steem/libraries/db2/database.cpp:1:
/home/steem/src/steem/libraries/db2/include/graphene/db2/timed_rw_lock.hpp:54:64: error: field ‘_current_lock’ has incomplete type ‘std::atomic<unsigned int>’
          std::atomic< uint32_t >                               _current_lock;
                                                                ^
```
Workaround:
add
`#include <atomic>`
in
`libraries/db2/include/graphene/db2/timed_rw_lock.hpp`

**Comment by Gandalf-the-Grey** [comment]
Fixed in current develop (merged shared-db)
