### ISSUE TITLE
FC does not compile with Boost 1.62

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#503]
At least one other project has this issue, see https://github.com/facebook/folly/issues/413

Here is the error:

```
[ 12%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/thread/thread.cpp.o
In file included from /home/cc/graphene/opt/boost_1_62_0/include/boost/coroutine/stack_context.hpp:14:0,
                 from /home/cc/graphene/src/steem/libraries/fc/src/thread/context.hpp:12,
                 from /home/cc/graphene/src/steem/libraries/fc/src/thread/thread_d.hpp:5,
                 from /home/cc/graphene/src/steem/libraries/fc/src/thread/thread.cpp:5:
/home/cc/graphene/opt/boost_1_62_0/include/boost/coroutine/detail/config.hpp:17:4: warning: #warning "Boost.Coroutine is now deprecated. Please switch to Boost.Coroutine2. To disable this warning message, define BOOST_COROUTINE_NO_DEPRECATION_WARNING." [-Wcpp]
 #  warning                  "Boost.Coroutine is now deprecated. Please switch to Boost.Coroutine2. To disable this warning message, define BOOST_COROUTINE_NO_DEPRECATION_WARNING."
    ^
In file included from /home/cc/graphene/src/steem/libraries/fc/src/thread/thread_d.hpp:5:0,
                 from /home/cc/graphene/src/steem/libraries/fc/src/thread/thread.cpp:5:
/home/cc/graphene/src/steem/libraries/fc/src/thread/context.hpp: In constructor ‘fc::context::context(fc::thread*)’:
/home/cc/graphene/src/steem/libraries/fc/src/thread/context.hpp:103:21: error: expected type-specifier
      my_context(new bc::fcontext_t),
                     ^
In file included from /home/cc/graphene/opt/boost_1_62_0/include/boost/system/system_error.hpp:14:0,
                 from /home/cc/graphene/opt/boost_1_62_0/include/boost/thread/exceptions.hpp:22,
                 from /home/cc/graphene/opt/boost_1_62_0/include/boost/thread/pthread/thread_data.hpp:10,
                 from /home/cc/graphene/opt/boost_1_62_0/include/boost/thread/thread_only.hpp:17,
                 from /home/cc/graphene/opt/boost_1_62_0/include/boost/thread/thread.hpp:12,
                 from /home/cc/graphene/opt/boost_1_62_0/include/boost/thread.hpp:13,
                 from /home/cc/graphene/src/steem/libraries/fc/src/thread/thread_d.hpp:4,
                 from /home/cc/graphene/src/steem/libraries/fc/src/thread/thread.cpp:5:
/home/cc/graphene/opt/boost_1_62_0/include/boost/system/error_code.hpp: At global scope:
/home/cc/graphene/opt/boost_1_62_0/include/boost/system/error_code.hpp:221:36: warning: ‘boost::system::posix_category’ defined but not used [-Wunused-variable]
     static const error_category &  posix_category = generic_category();
                                    ^
/home/cc/graphene/opt/boost_1_62_0/include/boost/system/error_code.hpp:222:36: warning: ‘boost::system::errno_ecat’ defined but not used [-Wunused-variable]
     static const error_category &  errno_ecat     = generic_category();
                                    ^
/home/cc/graphene/opt/boost_1_62_0/include/boost/system/error_code.hpp:223:36: warning: ‘boost::system::native_ecat’ defined but not used [-Wunused-variable]
     static const error_category &  native_ecat    = system_category();
                                    ^
In file included from /home/cc/graphene/opt/boost_1_62_0/include/boost/container/detail/flat_tree.hpp:29:0,
                 from /home/cc/graphene/opt/boost_1_62_0/include/boost/container/flat_map.hpp:29,
                 from /home/cc/graphene/src/steem/libraries/fc/include/fc/container/flat_fwd.hpp:2,
                 from /home/cc/graphene/src/steem/libraries/fc/include/fc/reflect/typename.hpp:10,
                 from /home/cc/graphene/src/steem/libraries/fc/include/fc/reflect/reflect.hpp:19,
                 from /home/cc/graphene/src/steem/libraries/fc/include/fc/time.hpp:138,
                 from /home/cc/graphene/src/steem/libraries/fc/include/fc/thread/future.hpp:3,
                 from /home/cc/graphene/src/steem/libraries/fc/include/fc/thread/task.hpp:2,
                 from /home/cc/graphene/src/steem/libraries/fc/include/fc/thread/thread.hpp:5,
                 from /home/cc/graphene/src/steem/libraries/fc/src/thread/thread.cpp:1:
/home/cc/graphene/opt/boost_1_62_0/include/boost/container/detail/pair.hpp:85:30: warning: ‘boost::container::piecewise_construct’ defined but not used [-Wunused-variable]
 static piecewise_construct_t piecewise_construct = BOOST_CONTAINER_DOC1ST(unspecified, *std_piecewise_construct_holder<>::dummy);
```

**Comment by bytemaster** [comment]
I have gotten much of FC compiling on 1.62, but will need to create a new branch for it.

**Comment by mvandeberg** [comment]
This is one of the priorities after #1301

**Comment by mvandeberg** [comment]
Steem builds with modern Boost, closing.
